import 'dart:io';

import 'package:dio/dio.dart';
import '../model/reqres_model.dart';
import '../model/resource_model.dart';

abstract class IASYService {
  IASYService(this.dio);
  final Dio dio;

  Future<Autogenerated?> fetchResourceItem();
}

enum _ASYPath { resource }

class ASYService extends IASYService {
  ASYService(super.dio);

  @override
  Future<Autogenerated?> fetchResourceItem() async {
    final response = await dio.post('/${_ASYPath.resource.name}');

    if (response.statusCode == HttpStatus.ok) {
      final jsonBody = response.data;
      if (jsonBody is Map<String, dynamic>) {
        return Autogenerated.fromJson(jsonBody);
      }
    }
    return null;
  }
}
